{
 "title": "Exhort",
 "description": "Trusted Content Exhort service",
 "tags": [
  "exhort",
  "trusted-content"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "exhort-stage,exhort-production" },
   { "name": "slo_time_window", "query": "28" },
   { "name": "slo_availability_objective", "query": "95" },
   { "name": "slo_latency_objective", "query": "95" },
   { "name": "cloudwatch_datasource", "query": "cloudwatch" },
   {
    "name": "region",
    "label": "Region",
    "query": {}
   },
   {
    "name": "cacheclusterId",
    "label": "CacheClusterID",
    "query": {}
   },
   {
    "name": "cachenodeid",
    "label": "CacheNodeId",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS (Total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\", job=\"exhort\"}[2m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "RPS (by endpoint)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\", job=\"exhort\"}[2m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS (by pod)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\", job=\"exhort\"}[2m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\", job=\"exhort\", status!~\"5..\"}[2m]))\n/\nsum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\", job=\"exhort\"}[2m]))",
     "legendFormat": "Availability"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=\"/api/v4/analysis\"}[2m])) by (le))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=\"/api/v4/analysis\"}[2m])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=\"/api/v4/analysis\"}[2m])) by (le))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\", job=\"exhort\"}[2m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Snyk latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(camel_route_policy_seconds_bucket{routeId=\"snykRequest\"}[2m])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(camel_route_policy_seconds_bucket{routeId=\"snykRequest\"}[2m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(camel_route_policy_seconds_bucket{routeId=\"snykRequest\"}[2m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Trusted Content latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(camel_route_policy_seconds_bucket{routeId=\"getTrustedContent\"}[2m])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(camel_route_policy_seconds_bucket{routeId=\"getTrustedContent\"}[2m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(camel_route_policy_seconds_bucket{routeId=\"getTrustedContent\"}[2m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "ONGuard latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(camel_route_policy_seconds_bucket{routeId=\"osvRequest\"}[2m])))",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(camel_route_policy_seconds_bucket{routeId=\"osvRequest\"}[2m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(camel_route_policy_seconds_bucket{routeId=\"osvRequest\"}[2m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=\"${namespace}\", container=\"app\", pod=~\"exhort.+\"}[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"${namespace}\", container=\"app\", pod=~\"exhort.+\"}) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "topk(1, kube_pod_container_resource_limits{namespace=\"${namespace}\", container=\"app\",resource=\"memory\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"${namespace}\", pod=~\"exhort.+\"}[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"${namespace}\", pod=~\"exhort.+\"}[5m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "SLO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Availability ($slo_time_window days)",
     "type": "stat",
     "description": "$slo_availability_objective percent of requests result in successful (non-5xx) response.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\", job=\"exhort\", status!~\"5..\"}[28d]))\n/\nsum(rate(http_server_requests_seconds_count{namespace=~\"$namespace\", job=\"exhort\"}[28d]))",
       "legendFormat": "Availability"
      }
     ]
    },
    {
     "title": "Latency ($slo_time_window days)",
     "type": "stat",
     "description": "$slo_latency_objective percent of requests services in <5000ms.\n",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{ status!~\"5..\", uri=\"/api/v4/analysis\"}[28d])) by (le))",
       "legendFormat": "0.95"
      }
     ]
    },
    {
     "title": "[ TDB] Error budget ($slo_time_window days)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } }
    }
   ]
  },
  {
   "title": "Elasticache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "CacheItems",
     "type": "stat",
     "description": "The number of items in the cache",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dimensions": { "CacheClusterId": "$cacheclusterId" },
       "metricName": "CurrItems",
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "DatabaseMemoryUsagePercentage",
     "type": "stat",
     "description": "Percentage of the memory for the cluster that is in use",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dimensions": { "CacheClusterId": "$cacheclusterId" },
       "metricName": "DatabaseMemoryUsagePercentage",
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "CacheHitRate",
     "type": "timeseries",
     "description": "Indicates the usage efficiency of the Redis instance. If the cache ratio is lower than about 0.8, it means that a significant amount of keys are evicted, expired, or don't exist",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "dimensions": { "CacheClusterId": "$cacheclusterId" },
       "metricName": "CacheHitRate",
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "BytesUsedForCache",
     "type": "timeseries",
     "description": "The total number of bytes allocated by Redis for all purposes, including the dataset, buffers, and so on.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "dimensions": { "CacheClusterId": "$cacheclusterId" },
       "metricName": "BytesUsedForCache",
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Evictions",
     "type": "stat",
     "description": "The number of keys that have been evicted due to the maxmemory limit",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dimensions": { "CacheClusterId": "$cacheclusterId" },
       "metricName": "Evictions",
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "DatabaseCapacityUsagePercentage",
     "type": "stat",
     "description": "Percentage of the total data capacity for the cluster that is in use",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dimensions": { "CacheClusterId": "$cacheclusterId" },
       "metricName": "DatabaseCapacityUsagePercentage",
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Elasticache host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPUUtilization",
     "type": "timeseries",
     "description": "The percentage of CPU utilization for the entire host",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "label": "CPUUtilization",
       "metricName": "CPUUtilization",
       "metricQueryType": 1,
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "$region",
       "sql": {
        "from": { "property": { "name": "AWS/ElastiCache", "type": "string" }, "type": "property" },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "CPUUtilization", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "$cacheclusterId" }, "property": { "name": "CacheClusterId", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT AVG(CPUUtilization) FROM \"AWS/ElastiCache\" WHERE CacheClusterId = '$cacheclusterId'",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "FreeableMemory",
     "type": "timeseries",
     "description": "The amount of free memory available on the host",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "label": "FreeableMemory",
       "metricQueryType": 1,
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "$region",
       "sql": {
        "from": { "property": { "name": "AWS/ElastiCache", "type": "string" }, "type": "property" },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "FreeableMemory", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "$cacheclusterId" }, "property": { "name": "CacheClusterId", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT AVG(FreeableMemory) FROM \"AWS/ElastiCache\" WHERE CacheClusterId = '$cacheclusterId'",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "SwapUsage",
     "type": "timeseries",
     "description": "The amount of swap used on the host.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "label": "SwapUsage",
       "metricQueryType": 1,
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "$region",
       "sql": {
        "from": { "property": { "name": "AWS/ElastiCache", "type": "string" }, "type": "property" },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "SwapUsage", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "$cacheclusterId" }, "property": { "name": "CacheClusterId", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT AVG(SwapUsage) FROM \"AWS/ElastiCache\" WHERE CacheClusterId = '$cacheclusterId'",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "EngineCPUUtilization",
     "type": "timeseries",
     "description": "Provides CPU utilization of the Redis engine thread",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "label": "EngineCPUUtilization",
       "metricQueryType": 1,
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "$region",
       "sql": {
        "from": { "property": { "name": "AWS/ElastiCache", "type": "string" }, "type": "property" },
        "select": {
         "name": "AVG",
         "parameters": [
          { "name": "EngineCPUUtilization", "type": "functionParameter" }
         ],
         "type": "function"
        },
        "where": {
         "expressions": [
          { "operator": { "name": "=", "value": "$cacheclusterId" }, "property": { "name": "CacheClusterId", "type": "string" }, "type": "operator" }
         ],
         "type": "and"
        }
       },
       "sqlExpression": "SELECT AVG(EngineCPUUtilization) FROM \"AWS/ElastiCache\" WHERE CacheClusterId = '$cacheclusterId'",
       "statistic": "Average"
      }
     ]
    }
   ]
  }
 ]
}